
/** AI Features module */
import { esc, notify } from "./utils.js";
import { getEditor } from "./editor.js";
function loadGoals(){try{return JSON.parse(localStorage.getItem("ycorrectGoals")||"{}")}catch{return{}}}
function vh(t){return "<div class=\"variant\"><div class=\"ai-text\">"+esc(t)+"</div><div class=\"ai-actions\"><button class=\"btn ghost small\" data-replace=\""+esc(t)+"\">Replace</button><button class=\"btn ghost small\" data-copy=\""+esc(t)+"\">Copy</button></div></div>"}
async function hc(){const p=document.querySelector("#composePrompt").value.trim();if(!p)return notify("Enter a prompt first.");const g=document.querySelector("#composeGenre").value;const o=document.querySelector("#composeOut");o.innerHTML="<div class=\"ai-loading\">Generating...</div>";try{const r=await fetch("/api/compose",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({prompt:p,genre:g,audience:loadGoals().audience||"General"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Compose failed");o.innerHTML=vh(d.text)}catch(e){o.innerHTML="<div class=\"ai-error\">"+esc(e.message)+"</div>"}}
async function hd(){const t=getEditor().value.trim();if(!t)return notify("Write some text first.");const o=document.querySelector("#detectOut");o.innerHTML="<div class=\"ai-loading\">Analyzing...</div>";try{const r=await fetch("/api/detect-ai",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({text:t.slice(0,10000)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Detection failed");const sc=d.score||0;const co=sc>70?"#ef4444":sc>40?"#f59e0b":"#10b981";o.innerHTML="<div style=\"text-align:center;padding:20px\"><div style=\"font-size:48px;font-weight:700;color:\">"+co+"<div style=\"font-size:13px;margin-top:8px\">"+esc(d.reason||"")+"</div></div>"}catch(e){o.innerHTML="<div class=\"ai-error\">"+esc(e.message)+"</div>"}}
async function hi(){const s=document.querySelector("#citeSource").value.trim();if(!s)return notify("Enter a URL or DOI first.");const y=document.querySelector("#citeStyle").value;const o=document.querySelector("#citeOut");o.innerHTML="<div class=\"ai-loading\">Generating citation...</div>";try{const r=await fetch("/api/cite",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({source:s,style:y})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Citation failed");o.innerHTML="<div class=\"variant\"><div class=\"ai-text\">"+esc(d.citation)+"</div><div class=\"ai-actions\"><button class=\"btn ghost small\" data-copy=\""+esc(d.citation)+"\">Copy</button></div></div>"}catch(e){o.innerHTML="<div class=\"ai-error\">"+esc(e.message)+"</div>"}}
export function initAIFeatures(){const a=document.querySelector("#composeBtn");if(a)a.addEventListener("click",hc);const b=document.querySelector("#detectBtn");if(b)b.addEventListener("click",hd);const ci=document.querySelector("#citeBtn");if(ci)ci.addEventListener("click",hi);const tr=document.querySelector("#translateBtn");if(tr)tr.addEventListener("click",ht);const vb=document.querySelector("#vocabBtn");if(vb)vb.addEventListener("click",hv)}
async function ht(){const t=getEditor().value.trim();if(!t)return notify("Write some text first.");const l=document.querySelector("#translateLang").value;const o=document.querySelector("#translateOut");o.innerHTML="<div class=\"ai-loading\">Translating...</div>";try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({text:t,targetLanguage:l})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Translation failed");o.innerHTML="<div class=\"variant\"><div class=\"ai-text\">"+esc(d.translation)+"</div><div class=\"ai-actions\"><button class=\"btn ghost small\" data-replace=\""+esc(d.translation)+"\">Replace</button><button class=\"btn ghost small\" data-copy=\""+esc(d.translation)+"\">Copy</button></div></div>"}catch(e){o.innerHTML="<div class=\"ai-error\">"+esc(e.message)+"</div>"}}
async function hv(){const t=getEditor().value.trim();if(!t)return notify("Write some text first.");const o=document.querySelector("#vocabOut");o.innerHTML="<div class=\"ai-loading\">Analyzing...</div>";try{const r=await fetch("/api/vocabulary",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({text:t.slice(0,5000)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed");let h="<div style=\"padding:8px\">";if(d.suggestions&&d.suggestions.length){d.suggestions.forEach(function(s){h+="<div style=\"margin-bottom:8px;padding:8px;border-radius:6px;border:1px solid #e2e8f0\"><b>"+esc(s.word)+"</b> -> <b style=\"color:#10b981\">"+esc(s.replacement)+"</b><div style=\"font-size:12px;color:#718096\">"+esc(s.reason)+"</div></div>"})}else{h+= "No suggestions."}h+="</div>";o.innerHTML=h}catch(e){o.innerHTML="Error: "+esc(e.message)}}