
/** AI Features module */
import { esc, notify } from "./utils.js";
import { getEditor } from "./editor.js";
function loadGoals(){try{return JSON.parse(localStorage.getItem("ycorrectGoals")||"{}")}catch{return{}}}
function vh(t){return "<div class=\"variant\"><div class=\"ai-text\">"+esc(t)+"</div><div class=\"ai-actions\"><button class=\"btn ghost small\" data-replace=\""+esc(t)+"\">Replace</button><button class=\"btn ghost small\" data-copy=\""+esc(t)+"\">Copy</button></div></div>"}
async function hc(){const p=document.querySelector("#composePrompt").value.trim();if(!p)return notify("Enter a prompt first.");const g=document.querySelector("#composeGenre").value;const o=document.querySelector("#composeOut");o.innerHTML="<div class=\"ai-loading\">Generating...</div>";try{const r=await fetch("/api/compose",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({prompt:p,genre:g,audience:loadGoals().audience||"General"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Compose failed");o.innerHTML=vh(d.text)}catch(e){o.innerHTML="<div class=\"ai-error\">"+esc(e.message)+"</div>"}}
async function hd(){const t=getEditor().value.trim();if(!t)return notify("Write some text first.");const o=document.querySelector("#detectOut");o.innerHTML="<div class=\"ai-loading\">Analyzing...</div>";try{const r=await fetch("/api/detect-ai",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({text:t.slice(0,10000)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Detection failed");const sc=d.score||0;const co=sc>70?"#ef4444":sc>40?"#f59e0b":"#10b981";o.innerHTML="<div style=\"text-align:center;padding:20px\"><div style=\"font-size:48px;font-weight:700;color:\">"+co+"<div style=\"font-size:13px;margin-top:8px\">"+esc(d.reason||"")+"</div></div>"}catch(e){o.innerHTML="<div class=\"ai-error\">"+esc(e.message)+"</div>"}}
async function hi(){const s=document.querySelector("#citeSource").value.trim();if(!s)return notify("Enter a URL or DOI first.");const y=document.querySelector("#citeStyle").value;const o=document.querySelector("#citeOut");o.innerHTML="<div class=\"ai-loading\">Generating citation...</div>";try{const r=await fetch("/api/cite",{method:"POST",headers:{"Content-Type": "application/json"},body:JSON.stringify({source:s,style:y})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Citation failed");o.innerHTML="<div class=\"variant\"><div class=\"ai-text\">"+esc(d.citation)+"</div><div class=\"ai-actions\"><button class=\"btn ghost small\" data-copy=\""+esc(d.citation)+"\">Copy</button></div></div>"}catch(e){o.innerHTML="<div class=\"ai-error\">"+esc(e.message)+"</div>"}}
export function initAIFeatures(){const a=document.querySelector("#composeBtn");if(a)a.addEventListener("click",hc);const b=document.querySelector("#detectBtn");if(b)b.addEventListener("click",hd);const ci=document.querySelector("#citeBtn");if(ci)ci.addEventListener("click",hi)}